language: python

python:
  - "3.6"
  - "3.8"

install:
  - pip install -r requirements.txt
  - pip install .

script: pytest

deploy:
  provider: pypi
  user: __token__
  password:
    secure: i5dUY32oAchbxZ6+VdgXAjRWpsrE55pcPmHcV8FEy5BOY0QRM/Fbbvd6wpv+Sr9XgbbmlBQD0KjFkv2bv+ZRflHVSHEyjYzaR2u2IQRH/1sEHpTk9KkQcPKsigtPVahWQ+4BOyKWGoz3wVJ44fJrvvlGDdfNLsE0LPw52KJaCfImPV8X7Fy0EhXaF4ICpHWrCKGRzCE3eSsiA2CYI4ySIrGW9+d/PO4a/4wka1aKOybA/rndkKUCyi6oD1OtOmxjWjnyp4AJcSD32gcytRuS+/6erZ5Fo5AmWX9FtUu90GdSVK7pb+bEgiNM24lZGH5V/KkShMuNvtnr7qNKo98c9GLuz3HoNE1EMvsE2Yow1KDpOBUCqGy3qU8nI9AY2Ikpa/nEm3IWQzWo1zkFzrQ0o2rIdpB3gq8PqI85xd5SLcxnKgW10ZM/7GGNeGAPutJBR7XXDcrQiAUXL4nHNdu15JaJLcwKAEbat4RbTJj3PwKETxZIe+soHOkyuBYiq9OX0unFfe6blv8rfKtD0j1GR0ehWpx1JsvqqJwdjHGeQHpQCrMYUN4jnqGNUjlvEfoaecANYHIGU0Kjwy1M6aKPQdCfXj3Q0dkDvPt11bNOKwvZr3Xf2KjNiE7wvb1gvhf1UDHoZHvOgh1vHYEENj4Ddy5Yvv1oJ/QeGly/Z31OToQ=
  on:
    tags: true
